In [1]:
import os
print(os.listdir("/kaggle/input"))

['competitions']

In [2]:
import pandas as pd
import numpy as np

train = pd.read_csv("/kaggle/input/competitions/spaceship-titanic/train.csv")
test = pd.read_csv("/kaggle/input/competitions/spaceship-titanic/test.csv")


print("Train shape:", train.shape)
print("Test shape:", test.shape)

train.head()

Train shape: (8693, 14)
Test shape: (4277, 13)

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True

In [3]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8693 entries, 0 to 8692
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PassengerId   8693 non-null   object
 1   HomePlanet    8492 non-null   object
 2   CryoSleep     8476 non-null   object
 3   Cabin         8494 non-null   object
 4   Destination   8511 non-null   object
 5   Age           8514 non-null   float64
 6   VIP           8490 non-null   object
 7   RoomService   8512 non-null   float64
 8   FoodCourt     8510 non-null   float64
 9   ShoppingMall  8485 non-null   float64
 10  Spa           8510 non-null   float64
 11  VRDeck        8505 non-null   float64
 12  Name          8493 non-null   object
 13  Transported   8693 non-null   bool
dtypes: bool(1), float64(6), object(7)
memory usage: 891.5+ KB

In [4]:
train["Transported"].value_counts()

Transported
True     4378
False    4315
Name: count, dtype: int64

In [5]:
train["Transported"].value_counts(normalize=True)

Transported
True     0.503624
False    0.496376
Name: proportion, dtype: float64

In [6]:
train.isnull().sum().sort_values(ascending=False)

CryoSleep       217
ShoppingMall    208
VIP             203
HomePlanet      201
Name            200
Cabin           199
VRDeck          188
Spa             183
FoodCourt       183
Destination     182
RoomService     181
Age             179
PassengerId       0
Transported       0
dtype: int64

In [7]:
(train.isnull().mean()*100).sort_values(ascending=False)

CryoSleep       2.496261
ShoppingMall    2.392730
VIP             2.335212
HomePlanet      2.312205
Name            2.300702
Cabin           2.289198
VRDeck          2.162660
Spa             2.105142
FoodCourt       2.105142
Destination     2.093639
RoomService     2.082135
Age             2.059128
PassengerId     0.000000
Transported     0.000000
dtype: float64

In [8]:
categorical_cols = [
    "HomePlanet",
    "CryoSleep",
    "Destination",
    "VIP"
]

for col in categorical_cols:
    print("-----", col, "-----")
    print(train[col].value_counts())
    print()

----- HomePlanet -----
HomePlanet
Earth     4602
Europa    2131
Mars      1759
Name: count, dtype: int64

----- CryoSleep -----
CryoSleep
False    5439
True     3037
Name: count, dtype: int64

----- Destination -----
Destination
TRAPPIST-1e      5915
55 Cancri e      1800
PSO J318.5-22     796
Name: count, dtype: int64

----- VIP -----
VIP
False    8291
True      199
Name: count, dtype: int64

In [9]:
numerical_cols = [
    "Age",
    "RoomService",
    "FoodCourt",
    "ShoppingMall",
    "Spa",
    "VRDeck"
]

train[numerical_cols].describe()

,Age,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck
count,8514.000000,8512.000000,8510.000000,8485.000000,8510.000000,8505.000000
mean,28.827930,224.687617,458.077203,173.729169,311.138778,304.854791
std,14.489021,666.717663,1611.489240,604.696458,1136.705535,1145.717189
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,19.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,27.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,38.000000,47.000000,76.000000,27.000000,59.000000,46.000000
max,79.000000,14327.000000,29813.000000,23492.000000,22408.000000,24133.000000

In [10]:
train.groupby("CryoSleep")[[
    "RoomService",
    "FoodCourt",
    "ShoppingMall",
    "Spa",
    "VRDeck"
]].mean()

           RoomService   FoodCourt  ShoppingMall        Spa      VRDeck
CryoSleep
False       350.146772  713.004316    270.586504  486.09294  475.716165
True          0.000000    0.000000      0.000000    0.00000    0.000000

In [11]:
pd.crosstab(train["CryoSleep"], train["Transported"], normalize="index")

Transported     False     True
CryoSleep
False        0.671079  0.328921
True         0.182417  0.817583

In [12]:
pd.crosstab(train["HomePlanet"], train["Transported"], normalize="index")

Transported     False     True
HomePlanet
Earth        0.576054  0.423946
Europa       0.341154  0.658846
Mars         0.476976  0.523024

In [13]:
pd.crosstab(train["Destination"], train["Transported"], normalize="index")

Transported       False     True
Destination
55 Cancri e    0.390000  0.610000
PSO J318.5-22  0.496231  0.503769
TRAPPIST-1e    0.528825  0.471175

In [14]:
train.groupby("Transported")["Age"].describe()

              count       mean        std  min   25%   50%   75%   max
Transported
False        4226.0  29.922858  13.699262  0.0  21.0  27.0  38.0  79.0
True         4288.0  27.748834  15.151705  0.0  18.0  26.0  37.0  78.0

In [15]:
pd.crosstab(train["VIP"], train["Transported"], normalize="index")

Transported     False     True
VIP
False        0.493668  0.506332
True         0.618090  0.381910

In [16]:
train["Cabin"].str.split("/", expand=True).head()

   0  1  2
0  B  0  P
1  F  0  S
2  A  0  S
3  A  0  S
4  F  1  S

In [17]:
train["Cabin"].str.split("/", expand=True)[0].value_counts()

0
F    2794
G    2559
E     876
B     779
C     747
D     478
A     256
T       5
Name: count, dtype: int64

In [18]:
deck = train["Cabin"].str.split("/", expand=True)[0]

pd.crosstab(deck, train["Transported"], normalize="index")

Transported     False     True
0
A            0.503906  0.496094
B            0.265725  0.734275
C            0.319946  0.680054
D            0.566946  0.433054
E            0.642694  0.357306
F            0.560129  0.439871
G            0.483783  0.516217
T            0.800000  0.200000

In [19]:
train["Group"] = train["PassengerId"].str.split("_").str[0]

train["Group"].value_counts().describe()

count    6217.000000
mean        1.398263
std         0.944051
min         1.000000
25%         1.000000
50%         1.000000
75%         1.000000
max         8.000000
Name: count, dtype: float64

In [20]:
train["Group"].value_counts().head(10)

Group
9081    8
4005    8
8988    8
5133    8
4256    8
4498    8
8956    8
8796    8
0984    8
5885    8
Name: count, dtype: int64

In [21]:
# split cabin
train[["Deck", "CabinNum", "Side"]] = train["Cabin"].str.split("/", expand=True)

# group id already created earlier
train["GroupSize"] = train.groupby("Group")["Group"].transform("count")

train.head()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported,Group,Deck,CabinNum,Side,GroupSize
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False,0001,B,0,P,1
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True,0002,F,0,S,1
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False,0003,A,0,S,2
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False,0003,A,0,S,2
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True,0004,F,1,S,1

In [22]:
train["TotalSpend"] = (
    train["RoomService"]
    + train["FoodCourt"]
    + train["ShoppingMall"]
    + train["Spa"]
    + train["VRDeck"]
)

In [23]:
train["NoSpend"] = (train["TotalSpend"] == 0).astype(int)

In [24]:
train = train.drop(columns=["PassengerId", "Cabin", "Name"])

In [25]:
train.head()

,HomePlanet,CryoSleep,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported,Group,Deck,CabinNum,Side,GroupSize,TotalSpend,NoSpend
0,Europa,False,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,False,0001,B,0,P,1,0.0,1
1,Earth,False,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,True,0002,F,0,S,1,736.0,0
2,Europa,False,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,False,0003,A,0,S,2,10383.0,0
3,Europa,False,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,False,0003,A,0,S,2,5176.0,0
4,Earth,False,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,True,0004,F,1,S,1,1091.0,0

In [26]:
train.columns

Index(['HomePlanet', 'CryoSleep', 'Destination', 'Age', 'VIP', 'RoomService',
       'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck', 'Transported', 'Group',
       'Deck', 'CabinNum', 'Side', 'GroupSize', 'TotalSpend', 'NoSpend'],
      dtype='object')

In [27]:
train = train.drop(columns=["Group"])

In [28]:
train.columns

Index(['HomePlanet', 'CryoSleep', 'Destination', 'Age', 'VIP', 'RoomService',
       'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck', 'Transported', 'Deck',
       'CabinNum', 'Side', 'GroupSize', 'TotalSpend', 'NoSpend'],
      dtype='object')

In [29]:
test_ids = test["PassengerId"].copy()

test["Group"] = test["PassengerId"].str.split("_").str[0]
test[["Deck", "CabinNum", "Side"]] = test["Cabin"].str.split("/", expand=True)

test["GroupSize"] = test.groupby("Group")["Group"].transform("count")

test["TotalSpend"] = (
    test["RoomService"]
    + test["FoodCourt"]
    + test["ShoppingMall"]
    + test["Spa"]
    + test["VRDeck"]
)

test["NoSpend"] = (test["TotalSpend"] == 0).astype(int)

test = test.drop(columns=["PassengerId", "Cabin", "Name", "Group"])

In [30]:
print(train.columns)
print(test.columns)

Index(['HomePlanet', 'CryoSleep', 'Destination', 'Age', 'VIP', 'RoomService',
       'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck', 'Transported', 'Deck',
       'CabinNum', 'Side', 'GroupSize', 'TotalSpend', 'NoSpend'],
      dtype='object')
Index(['HomePlanet', 'CryoSleep', 'Destination', 'Age', 'VIP', 'RoomService',
       'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck', 'Deck', 'CabinNum',
       'Side', 'GroupSize', 'TotalSpend', 'NoSpend'],
      dtype='object')

In [31]:
train["CabinNum"] = pd.to_numeric(train["CabinNum"], errors="coerce")
test["CabinNum"] = pd.to_numeric(test["CabinNum"], errors="coerce")

In [32]:
print(train["CabinNum"].dtype)
print(test["CabinNum"].dtype)

float64
float64

In [33]:
train["IsAlone"] = (train["GroupSize"] == 1).astype(int)
test["IsAlone"] = (test["GroupSize"] == 1).astype(int)

In [34]:
print(train["IsAlone"].value_counts())

IsAlone
1    4805
0    3888
Name: count, dtype: int64

In [35]:
train["AgeGroup"] = pd.cut(
    train["Age"],
    bins=[-1, 12, 18, 35, 50, 100],
    labels=["Child", "Teen", "YoungAdult", "Adult", "Senior"]
)

test["AgeGroup"] = pd.cut(
    test["Age"],
    bins=[-1, 12, 18, 35, 50, 100],
    labels=["Child", "Teen", "YoungAdult", "Adult", "Senior"]
)

In [36]:
print(train["AgeGroup"].value_counts(dropna=False))

AgeGroup
YoungAdult    4136
Adult         1776
Teen          1059
Child          806
Senior         737
NaN            179
Name: count, dtype: int64

In [37]:
train["SpendPerPerson"] = train["TotalSpend"] / train["GroupSize"]
test["SpendPerPerson"] = test["TotalSpend"] / test["GroupSize"]

In [38]:
print(train["SpendPerPerson"].describe())

count     7785.000000
mean      1014.852396
std       2006.512332
min          0.000000
25%          0.000000
50%        483.500000
75%       1052.000000
max      35987.000000
Name: SpendPerPerson, dtype: float64

In [39]:
train["CabinGroup"] = train["Deck"].astype(str) + "_" + train["Side"].astype(str)
test["CabinGroup"] = test["Deck"].astype(str) + "_" + test["Side"].astype(str)

In [40]:
print(train["CabinGroup"].value_counts().head(10))

CabinGroup
F_P    1438
F_S    1356
G_S    1283
G_P    1276
E_S     447
E_P     429
B_S     426
C_S     406
B_P     353
C_P     341
Name: count, dtype: int64

In [41]:
train["VIP_CryoSleep"] = train["VIP"].astype(str) + "_" + train["CryoSleep"].astype(str)
test["VIP_CryoSleep"] = test["VIP"].astype(str) + "_" + test["CryoSleep"].astype(str)

In [42]:
print(train["VIP_CryoSleep"].value_counts())

VIP_CryoSleep
False_False    5143
False_True     2941
False_nan       207
True_False      175
nan_False       121
nan_True         75
True_True        21
nan_nan           7
True_nan          3
Name: count, dtype: int64

In [43]:
train["PlanetDestination"] = train["HomePlanet"].astype(str) + "_" + train["Destination"].astype(str)
test["PlanetDestination"] = test["HomePlanet"].astype(str) + "_" + test["Destination"].astype(str)

In [44]:
print(train["PlanetDestination"].value_counts().head(10))

PlanetDestination
Earth_TRAPPIST-1e      3101
Mars_TRAPPIST-1e       1475
Europa_TRAPPIST-1e     1189
Europa_55 Cancri e      886
Earth_PSO J318.5-22     712
Earth_55 Cancri e       690
Mars_55 Cancri e        193
nan_TRAPPIST-1e         150
Earth_nan                99
Mars_PSO J318.5-22       49
Name: count, dtype: int64

In [45]:
for col in ["RoomService", "FoodCourt", "ShoppingMall", "Spa", "VRDeck", "TotalSpend"]:
    train[f"log_{col}"] = np.log1p(train[col])
    test[f"log_{col}"] = np.log1p(test[col])

In [46]:
print(train["log_TotalSpend"].describe())

count    7785.000000
mean        4.305709
std         3.700501
min         0.000000
25%         0.000000
50%         6.602588
75%         7.304516
max        10.490941
Name: log_TotalSpend, dtype: float64

In [47]:
train["log_SpendPerPerson"] = np.log1p(train["SpendPerPerson"])
test["log_SpendPerPerson"] = np.log1p(test["SpendPerPerson"])

In [48]:
print(train["log_SpendPerPerson"].describe())

count    7785.000000
mean        4.081812
std         3.519985
min         0.000000
25%         0.000000
50%         6.183117
75%         6.959399
max        10.490941
Name: log_SpendPerPerson, dtype: float64

In [49]:
train["CabinRegion"] = pd.qcut(train["CabinNum"], q=6, duplicates="drop").astype(str)

cabin_bins = np.unique(np.quantile(train["CabinNum"].dropna(), q=np.linspace(0, 1, 7)))

test["CabinRegion"] = pd.cut(
    test["CabinNum"],
    bins=cabin_bins,
    include_lowest=True
).astype(str)

In [50]:
print(train["CabinRegion"].value_counts())

CabinRegion
(-0.001, 107.0]     1429
(107.0, 230.0]      1420
(789.0, 1219.0]     1418
(1219.0, 1894.0]    1414
(427.0, 789.0]      1412
(230.0, 427.0]      1401
nan                  199
Name: count, dtype: int64

In [51]:
catboost_features = [
    "HomePlanet",
    "CryoSleep",
    "Destination",
    "Age",
    "VIP",
    "RoomService",
    "FoodCourt",
    "ShoppingMall",
    "Spa",
    "VRDeck",
    "Deck",
    "CabinNum",
    "Side",
    "GroupSize",
    "TotalSpend",
    "NoSpend",
    "IsAlone",
    "AgeGroup",
    "SpendPerPerson",
    "CabinGroup",
    "VIP_CryoSleep",
    "PlanetDestination",
    "log_RoomService",
    "log_FoodCourt",
    "log_ShoppingMall",
    "log_Spa",
    "log_VRDeck",
    "log_TotalSpend",
    "log_SpendPerPerson",
    "CabinRegion"
]

catboost_categorical = [
    "HomePlanet",
    "CryoSleep",
    "Destination",
    "VIP",
    "Deck",
    "Side",
    "AgeGroup",
    "CabinGroup",
    "VIP_CryoSleep",
    "PlanetDestination",
    "CabinRegion"
]

print("Total features:", len(catboost_features))
print("Categorical features:", catboost_categorical)

Total features: 30
Categorical features: ['HomePlanet', 'CryoSleep', 'Destination', 'VIP', 'Deck', 'Side', 'AgeGroup', 'CabinGroup', 'VIP_CryoSleep', 'PlanetDestination', 'CabinRegion']

In [52]:
# categorical features -> replace NaN with "Missing"
for col in catboost_categorical:
    train[col] = train[col].astype(object).where(train[col].notna(), "Missing")
    test[col] = test[col].astype(object).where(test[col].notna(), "Missing")

# numeric features -> fill with train median
catboost_numeric = [col for col in catboost_features if col not in catboost_categorical]

for col in catboost_numeric:
    median_value = train[col].median()
    train[col] = train[col].fillna(median_value)
    test[col] = test[col].fillna(median_value)

print("Train missing:", train[catboost_features].isnull().sum().sum())
print("Test missing:", test[catboost_features].isnull().sum().sum())

Train missing: 0
Test missing: 0

In [53]:
from catboost import CatBoostClassifier

In [54]:
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score
from catboost import CatBoostClassifier
import numpy as np

X_cv = train[catboost_features]
y_cv = train["Transported"]

cat_features_idx = [X_cv.columns.get_loc(col) for col in catboost_categorical]

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

cv_scores = []

for fold, (train_idx, val_idx) in enumerate(cv.split(X_cv, y_cv), 1):
    X_train_fold = X_cv.iloc[train_idx]
    X_val_fold = X_cv.iloc[val_idx]
    y_train_fold = y_cv.iloc[train_idx]
    y_val_fold = y_cv.iloc[val_idx]

    cv_model = CatBoostClassifier(
        iterations=2000,
        learning_rate=0.03,
        depth=8,
        loss_function="Logloss",
        eval_metric="Accuracy",
        random_seed=42,
        verbose=0
    )

    cv_model.fit(
        X_train_fold,
        y_train_fold,
        cat_features=cat_features_idx,
        eval_set=(X_val_fold, y_val_fold),
        use_best_model=True
    )

    val_pred = cv_model.predict(X_val_fold)
    fold_score = accuracy_score(y_val_fold, val_pred)
    cv_scores.append(fold_score)

    print(f"Fold {fold} accuracy: {fold_score:.6f}")

cv_scores = np.array(cv_scores)

print("\nCV scores:", cv_scores)
print("Mean CV accuracy:", cv_scores.mean())
print("Std CV accuracy:", cv_scores.std())

Fold 1 accuracy: 0.826912
Fold 2 accuracy: 0.813111
Fold 3 accuracy: 0.821162
Fold 4 accuracy: 0.830265
Fold 5 accuracy: 0.808400

CV scores: [0.82691202 0.81311098 0.82116159 0.83026467 0.80840046]
Mean CV accuracy: 0.8199699442360364
Std CV accuracy: 0.008203561791455776

In [55]:
from sklearn.model_selection import train_test_split

X_cb = train[catboost_features]
y_cb = train["Transported"]

X_train_cb, X_val_cb, y_train_cb, y_val_cb = train_test_split(
    X_cb,
    y_cb,
    test_size=0.2,
    stratify=y_cb,
    random_state=42
)

print(X_train_cb.shape)
print(X_val_cb.shape)

(6954, 30)
(1739, 30)

In [56]:
from catboost import CatBoostClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

cat_features_idx = [X_train_cb.columns.get_loc(col) for col in catboost_categorical]

cat_model = CatBoostClassifier(
    iterations=2000,
    learning_rate=0.03,
    depth=8,
    loss_function="Logloss",
    eval_metric="Accuracy",
    random_seed=42,
    verbose=200
)

cat_model.fit(
    X_train_cb,
    y_train_cb,
    cat_features=cat_features_idx,
    eval_set=(X_val_cb, y_val_cb),
    use_best_model=True
)

cb_val_pred = cat_model.predict(X_val_cb)

print("Validation accuracy:", accuracy_score(y_val_cb, cb_val_pred))
print()
print(classification_report(y_val_cb, cb_val_pred))
print()
print(confusion_matrix(y_val_cb, cb_val_pred))

0:	learn: 0.7532355	test: 0.7573318	best: 0.7573318 (0)	total: 35.6ms	remaining: 1m 11s
200:	learn: 0.8387978	test: 0.8021852	best: 0.8033353 (148)	total: 6.93s	remaining: 1m 2s
400:	learn: 0.8730227	test: 0.8108108	best: 0.8108108 (399)	total: 14.1s	remaining: 56.3s
600:	learn: 0.8996261	test: 0.8136860	best: 0.8165612 (568)	total: 21.6s	remaining: 50.2s
800:	learn: 0.9229221	test: 0.8182864	best: 0.8182864 (720)	total: 29s	remaining: 43.4s
1000:	learn: 0.9370147	test: 0.8165612	best: 0.8182864 (720)	total: 36.4s	remaining: 36.3s
1200:	learn: 0.9505321	test: 0.8182864	best: 0.8194365 (1186)	total: 44.1s	remaining: 29.3s
1400:	learn: 0.9627552	test: 0.8200115	best: 0.8217366 (1391)	total: 51.7s	remaining: 22.1s
1600:	learn: 0.9723900	test: 0.8200115	best: 0.8223117 (1413)	total: 59.2s	remaining: 14.7s
1800:	learn: 0.9788611	test: 0.8200115	best: 0.8228867 (1666)	total: 1m 6s	remaining: 7.37s
1999:	learn: 0.9824561	test: 0.8205865	best: 0.8228867 (1666)	total: 1m 14s	remaining: 0us

bestTest = 0.8228867165
bestIteration = 1666

Shrink model to first 1667 iterations.
Validation accuracy: 0.8228867165037378

              precision    recall  f1-score   support

       False       0.81      0.83      0.82       863
        True       0.83      0.81      0.82       876

    accuracy                           0.82      1739
   macro avg       0.82      0.82      0.82      1739
weighted avg       0.82      0.82      0.82      1739


[[720 143]
 [165 711]]

In [57]:
X_full_cb = train[catboost_features]
y_full_cb = train["Transported"]
X_test_cb = test[catboost_features]

cat_features_idx_full = [X_full_cb.columns.get_loc(col) for col in catboost_categorical]

final_cat_model = CatBoostClassifier(
    iterations=2000,
    learning_rate=0.03,
    depth=8,
    loss_function="Logloss",
    eval_metric="Accuracy",
    random_seed=42,
    verbose=200
)

final_cat_model.fit(
    X_full_cb,
    y_full_cb,
    cat_features=cat_features_idx_full
)

test_pred_cb = final_cat_model.predict(X_test_cb)

0:	learn: 0.7740711	total: 41.9ms	remaining: 1m 23s
200:	learn: 0.8414817	total: 7.58s	remaining: 1m 7s
400:	learn: 0.8727712	total: 15.3s	remaining: 1m
600:	learn: 0.8973887	total: 23.1s	remaining: 53.8s
800:	learn: 0.9168296	total: 31.1s	remaining: 46.6s
1000:	learn: 0.9331646	total: 39.1s	remaining: 39s
1200:	learn: 0.9473139	total: 47s	remaining: 31.3s
1400:	learn: 0.9569769	total: 55s	remaining: 23.5s
1600:	learn: 0.9654895	total: 1m 3s	remaining: 15.7s
1800:	learn: 0.9714713	total: 1m 11s	remaining: 7.88s
1999:	learn: 0.9768779	total: 1m 19s	remaining: 0us

In [58]:
submission = pd.DataFrame({
    "PassengerId": test_ids,
    "Transported": test_pred_cb.astype(bool)
})

submission.to_csv("submission.csv", index=False)
submission.head()

  PassengerId  Transported
0     0013_01        False
1     0018_01        False
2     0019_01         True
3     0021_01         True
4     0023_01        False